// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VKContest2023.API.DBData;

#nullable disable

namespace VKContest2023.API.Migrations
{
    [DbContext(typeof(DBConfigContext))]
    partial class DBConfigContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VKContest2023.API.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("created_date");

                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("user_group_id");

                    b.Property<int>("UserStateId")
                        .HasColumnType("integer")
                        .HasColumnName("user_state_id");

                    b.HasKey("Id");

                    b.HasIndex("UserGroupId");

                    b.HasIndex("UserStateId");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateOnly(2023, 5, 10),
                            Login = "Old Ilya",
                            Password = "asdfasdf",
                            UserGroupId = 1,
                            UserStateId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateOnly(2023, 5, 10),
                            Login = "Ilya",
                            Password = "345235234",
                            UserGroupId = 2,
                            UserStateId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateOnly(2023, 5, 10),
                            Login = "You",
                            Password = "345235234df",
                            UserGroupId = 1,
                            UserStateId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateOnly(2023, 5, 10),
                            Login = "UserUser",
                            Password = "3452f",
                            UserGroupId = 1,
                            UserStateId = 1
                        });
                });

            modelBuilder.Entity("VKContest2023.API.Model.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("user_group", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Admin",
                            Description = "Actual Administrator!"
                        },
                        new
                        {
                            Id = 2,
                            Code = "User",
                            Description = "I'm only user after all..."
                        });
                });

            modelBuilder.Entity("VKContest2023.API.Model.UserState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("user_state", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Active",
                            Description = "User can use and be used!"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Blocked",
                            Description = "Deleted user."
                        });
                });

            modelBuilder.Entity("VKContest2023.API.Model.User", b =>
                {
                    b.HasOne("VKContest2023.API.Model.UserGroup", "UserGroup")
                        .WithMany()
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VKContest2023.API.Model.UserState", "UserState")
                        .WithMany()
                        .HasForeignKey("UserStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserGroup");

                    b.Navigation("UserState");
                });
#pragma warning restore 612, 618
        }
    }
}
